### ISSUE TITLE
Better way to untar `.tar.gz`

### ISSUE THREAD

**Issue by madrix01** [bare-cli/bare#21]
We have tried different ways to untar the download repo from github. But untarring doesn't seem to work. We have tried different work arounds and found out a library `targz` but it was around 8 year old. What would be a better way to untar `.tar.gz`

**Comment by madrix01** [comment]
@godcrampy Can you help with this one ?

**Comment by godcrampy** [comment]
https://pkg.go.dev/archive/tar
Tired this?

**Comment by madrix01** [comment]
https://github.com/bare-cli/bare/blob/main/utils/osutil/zip.go

I have implemented this functions
